

export const CURRENT_STEP:string = "CURRENT_STEP";
export const UPDATE_USER_ROLE:string = "UPDATE_USER_ROLE";
export const ROLE:string = "ROLE";
export const ADD_GENERATED_WORKER_TAGS:string = "ADD_GENERATED_WORKER_TAGS";
export const ADD_SELECTED_WORKER_TAGS:string = "ADD_SELECTED_WORKER_TAGS";
export const REMOVE_SELECTED_WORKER_TAGS:string ="REMOVE_SELECTED_WORKER_TAGS";
export const REMOVE_GENERATED_WORKER_TAG:string = "REMOVE_GENERATED_WORKER_TAG";
export const UPDATE_SIGNUP_DATA:string = "UPDATE_SIGNUP_DATA";



